# name: Build Android

# on: [push, pull_request]

# jobs:
#     build:
#         name: Build APK
#         runs-on: ubuntu-latest
#         steps:
#             - name: Checkout source
#               uses: actions/checkout@v2

#             - name: Setup java
#               uses: actions/setup-java@v1
#               with:
#                   # java-version: 1.8
#                   java-version: 11

#             # - name: Setup Node.js
#             #   uses: actions/setup-node@v1
#             #   with:
#             #     node-version: 13.x

#             - name: Install Ionic
#               run: npm install -g @ionic/cli

#             - name: Install app dependencies
#               run: npm install

#             - name: Build Ionic App
#               run: ionic build

#             - name: Copy Android
#               run: ionic capacitor copy android

#             - name: Build Android Dev APK
#               run: ionic capacitor build android

#             - name: Build Android Release APK
#               run: ionic capacitor build android --release --prod

#             - name: Generate the Android App Bundle
#               working-directory: ./android/
#               run: ./gradlew bundle

#             - name: list
#               run: tree .

#             - name: Upload dev APK
#               uses: actions/upload-artifact@v1
#               with:
#                   name: app-dev
#                   path: ./android/apk/app-debug.apk

#             - name: Upload release bundle
#               uses: actions/upload-artifact@v1
#               with:
#                   name: app-release
#                   path: ./android/apk/app.aab

#             # - name: Save release bundle as artifact
#             #   uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # tag=v3
#             #   with:
#             #     name: app-release
#             #     path: |
#             #       ${{ github.workspace }}/packages/app/android/app/build/outputs/bundle/release/*.aab
#             #       ${{ github.workspace }}/packages/app/android/app/build/outputs/apk/release/*.apk
